all:
	g++ --std=c++17 -I ~/usr/include/ uba2pba.cc dcamin.cc -o uba2pba -L/Users/qiyitang/usr/lib -lspot -lbddx -O3

	#g++ --std=c++17 uba2pba.cc dcamin.cc -o uba2pba -lspot -lbddx -O3

#------------------------------------------------------
clean: #clean
	rm -f *.o main *.cc~ *.h~ Makefile~
#------------------------------------------------------

