all:
	g++ --std=c++17 uba2pba.cc dcamin.cc -o uba2pba -lspot -lbddx -O3

#------------------------------------------------------
clean: #clean
	rm -f *.o main *.cc~ *.h~ Makefile~
#------------------------------------------------------

