#! /bin/zsh

# Interface wrapper for calling Spot's ltl2tgba as a LTL->UBA tool
# Invoke from PRISM with
#  -ltluba -ltl2datool hoa-ltl2tgba-uba-for-prism -ltl2dasyntax lbt
#
# Expects the ltl2tgba executable on the PATH, otherwise
# specify the location using
export DUGGI=duggi
# before invoking PRISM
#
# You can disable the WDBA minimization phase of ltl2tgba to obtain
# UBA by setting
# export DUGGI_NOWDBA=0


# Take the ltl2tgba executable from the LTL2TGBA environment variable
# Otherwise, default to "ltl2tgba", which will search the PATH
DUGGI_BIN=${DUGGI-duggi}

# default to 0
DUGGI_NOWDBA=${DUGGI_NOWDBA-0}

XTRA_ARGS=""
if [ "$DUGGI_NOWDBA" -eq "1" ]; then
    XTRA_ARGS="-x wdba-minimize=0"
fi

# We don't use ltlfilt for LTL simplification anymore
# OPT_LTL=`ltlfilt --lbt-input --simplify=3 --lbt -F "$1"`
OPT_LTL=`cat $1`


# --output=automaton = we want the automaton
# --output-format=hoa = ... in HOA
# --ltl2nba = with ltl2tgba as LTL->NBA
#              -s -B = as Spin neverclaim, NBA output
${DUGGI} --u --ba ${OPT_LTL} | autfilt -B -C --high ${XTRA_ARGS} > $2
